version: "3"

volumes:
    produtosdata:
  
networks:
    frontend:
    backend:
    
services:
    mysql:
        image: "mysql:latest"
        volumes:
            - produtosdata:/var/lib/mysql
            - ./MySQL_Init_Script:/docker-entrypoint-initdb.d
        networks:
            - backend
        environment:
            - MYSQL_ROOT_PASSWORD=senha123
            - bind-address=0.0.0.0

